spring:
  application:
    name: jobportal
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true
server:
  port: 8081
jwt:
  secret: ${JWT_SECRET:}
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7